import os
from typing import List
from .interfaces import EncodedFileManager

class FileManager(EncodedFileManager):
    """Manages files generated by the MP4 encoder"""
    def get_file_paths(self, base_path: str) -> List[str]:
        """Returns [.mp4, _manifest.json, _faiss.index] files"""
        return [
            base_path,
            base_path.replace('.mp4', '_manifest.json'),
            base_path.replace('.mp4', '_faiss.index')
        ]